# .streamlit/secrets.toml

GEMINI_API_KEY = "AIzaSyCv1CwT5pWAF-fkj5nHjIrryu6F2gZeL9c"
SUPABASE_URL = "https://mmacplzzdrpezpfremul.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tYWNwbHp6ZHJwZXpwZnJlbXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNDYzMDUsImV4cCI6MjA3NDcyMjMwNX0.h7HMd8xYBz7RnxE1-G5RmowX_-Gn1u_l7NVEFDVwrOg"